version: "3.8"
services:
  # propiedades:
  #   build: .
  #   environment:
  #     - DB_USER=postgres
  #     - DB_PASSWORD=postgres
  #     - DB_HOST=propiedades_db
  #     - DB_PORT=5432
  #     - DB_NAME=propiedades
  #   restart: always
  #   networks:
  #     - app_net
  #   depends_on:
  #     propiedades_db:
  #       condition: service_healthy
  #   ports:
  #     - "3001:3000"

  propiedades_db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=propiedades
    ports:
      - "5432:5432"
    networks:
      - app_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  app_net:
    driver: bridge
